Added Stimulus example
shakacode/react-webpack-rails-tutorial pull request #492
Opened 2022-01-26 00:08 UTC by m15e

Example uses Stimulus to interact with Action Cable comments channel
- Stimulus "comments_controller.js" listens to comments channel and updates comment list when a new comment is added

2022-01-31 01:10 UTC, justin808 requested changes
I think it's odd for stimulus to be mixed with React, or maybe I'm not getting something.

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-:-MuhfbmJ3vQo2FPbM2CO:b-t15tw2)* status: all files reviewed, 6 unresolved discussions (waiting on @m15e)

___
*[dump.rdb, line 0 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MuhcuHt3f55jiHrdbTs:-MuhcuHt3f55jiHrdbTt:b22vy3a) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/dump.rdb#L0)):*
why are you adding this file?
___
*[Gemfile, line 6 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MuhcyZo28-GXECJ_8Jn:-MuhcyZo28-GXECJ_8Jo:b-6xrqj0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/Gemfile#L6)):*
> ```Ruby
> git_source(:github) { |repo| "https://github.com/#{repo}.git" }
> 
> ruby "3.0.3"
> ```

why are you updating to ruby 3 for this PR?

we like small, focused PRs
___
*[app/controllers/pages_controller.rb, line 38 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MuhdLW490KT14A0Pck6:-MuhdLW490KT14A0Pck7:bch6qp6) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/app/controllers/pages_controller.rb#L38)):*
> ```Ruby
> 
>   def stimulus
>     redux_store("commentsStore", props: comments_json_string)
> ```

can you refresh my memory on why you have the redux_store call here?
___
*[app/views/pages/stimulus.html.erb, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MuhdiZi-cZpQ-b07wb0:-MuhdiZi-cZpQ-b07wb1:b-qs3b5j) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/app/views/pages/stimulus.html.erb#L7)):*
> ```erb
> <!--Note, pre-rendering set in /config/initializers/react_on_rails.rb -->
> <%= react_component('StimulusApp') %>
>   
> ```

did you notice the red chars in the diff? Three is some junk at the end of the file.
___
*[client/app/bundles/comments/components/CommentBox/CommentBox.jsx, line 91 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MuhdwgODpxTFRIHus6u:-MuhdwgODpxTFRIHus6v:b4dxez2) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/client/app/bundles/comments/components/CommentBox/CommentBox.jsx#L91)):*
> ```JavaScript
>         <ul>
>           <li>
>             {(data.get('isFetching') && <br />) ||
> ```

why are you reformatting this file in this PR? This would be good for a separate PR.
___
*[client/app/bundles/comments/components/StimulusCommentBox/StimulusCommentBox.jsx, line 1 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-Muhf7LO38rTgl3jjq7w:-Muhf7LO38rTgl3jjq7x:b-g4tyyc) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/d88e00bb77c902ad0d70d82ff2dd35b256ab2e2e/client/app/bundles/comments/components/StimulusCommentBox/StimulusCommentBox.jsx#L1)):*
> ```JavaScript
> import React from 'react';
> ```

I'm very confused on why you are including React if you're using Stimulus. Please explain.


<!-- Sent from Reviewable.io -->

2022-02-03 20:10 UTC, bokoboshahni commented
My own use case for seeing this working is that I'm looking to potentially transition an application that currently uses Stimulus/Turbo over to React and will need them to run side-by-side for awhile.

2022-02-07 07:35 UTC, justin808 requested changes
Seems pretty good. I didn't run this yet.

The only thing I saw that needs changing as the files need resaving with an editor that deletes trailing spaces.

> Reviewed 8 of 12 files at r2, 22 of 24 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-:-MvI5WIvC1ZVNdacV2s0:b-6io5vq)* status: all files reviewed, 10 unresolved discussions (waiting on @m15e)

___
*[app/controllers/comments_controller.rb, line 29 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI3tOe9-Cfko9kMFFC:-MvI3tOe9-Cfko9kMFFD:bu8jd54) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/app/controllers/comments_controller.rb#L29)):*
> ```Ruby
>         if turbo_frame_request?
>           format.html
>         else  
> ```

@m15e see the red dots ^^^^. You have trailing spaces.
___
*[app/views/comments/turbo/_comment_list.html.erb, line 3 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI4QpE-kkxe4JwiBIC:-MvI4QpE-kkxe4JwiBID:b9c2kge) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/app/views/comments/turbo/_comment_list.html.erb#L3)):*
> ```erb
> <%= turbo_frame_tag "comment_list", data: { turbo: true } do %> 
>   <a href="<%= comment_list_path %>" data-comments-target="commentRefresh" style="display:none">
>     Hidden Refresh Button</a>
> ```

why a hidden refresh button?
___
*[client/app/assets/styles/bootstrap-pre-customizations.scss, line 63 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI4tBl4gf432RkJi8K:-MvI4tBl4gf432RkJi8L:b-hd2t48) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/client/app/assets/styles/bootstrap-pre-customizations.scss#L63)):*
> ```SCSS
> .w-50 {
>   width: 27vw!important;
> }
> ```

Is this the right file for this custom CSS?

TBH, we should switch from bootstrap to tailwind at some point!
___
*[client/app/packs/client-bundle.js, line 6 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI5I7vEHGZxtDqVrKZ:-MvI5I7vEHGZxtDqVrK_:b4nv5re) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/client/app/packs/client-bundle.js#L6)):*
> ```JavaScript
> import controllers from '../controllers';
> import { Turbo } from "@hotwired/turbo-rails";
> Turbo.session.drive = false;
> ```

Should we have a single bundle that includes Turbo? or have a separate bundle?


<!-- Sent from Reviewable.io -->

2022-02-07 14:50 UTC, m15e reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492)* status: 31 of 40 files reviewed, 10 unresolved discussions (waiting on @justin808 and @m15e)

___
*[app/views/comments/turbo/_comment_list.html.erb, line 3 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI4QpE-kkxe4JwiBIC:-MvJbr-B7WUnu60Fj6ZZ:b6opehb) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/app/views/comments/turbo/_comment_list.html.erb#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why a hidden refresh button?
</blockquote></details>

I'm still a little new to turbo frames and didn't know how else to trigger a frame-change from outside of the turbo frame. The "Force Refresh of All Comments" control was in a separate div from the turbo frame I wanted to change. I admit it's a bit hacky but I figured it would at least demonstrate the use of Stimulus interacting with a turbo frame. 

Would you know of a better way to approach this?
___
*[client/app/assets/styles/bootstrap-pre-customizations.scss, line 63 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI4tBl4gf432RkJi8K:-MvJdmR04wnaqUKx-OVW:b-jh6v06) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/client/app/assets/styles/bootstrap-pre-customizations.scss#L63)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Is this the right file for this custom CSS?

TBH, we should switch from bootstrap to tailwind at some point!
</blockquote></details>

I've moved the CSS to a separate file.

I agree Tailwind would be nice.
___
*[client/app/packs/client-bundle.js, line 6 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/492#-MvI5I7vEHGZxtDqVrKZ:-MvJeBOs3k19-RDy6nJa:blq2yla) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/227c03baca9aabb86bb221a5e8241d2e0716b40c/client/app/packs/client-bundle.js#L6)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Should we have a single bundle that includes Turbo? or have a separate bundle?
</blockquote></details>

I've created a separate bundle for the Stimulus example.


<!-- Sent from Reviewable.io -->

2022-02-22 10:41 UTC, kchivorn commented on app/views/comments/turbo/_comment_list.html.erb
> +    Hidden Refresh Button</a>
Move </a> to newline ?

2022-02-22 11:10 UTC, kchivorn commented on app/views/comments/turbo/_tabs.html.erb
> +    <li class="nav-item <%= @formType == "horizontal" ? "active" : "" %>" role="presentation">
How about using action_name to check the active status instead of creating instance variable @formType in the controller?

2022-02-22 11:12 UTC, kchivorn commented on app/controllers/comments_controller.rb
> +    @formType = "horizontal"
We might not need this instance variable @formType by using action_name instead.

2022-02-22 11:12 UTC, kchivorn commented on app/controllers/comments_controller.rb
> +    @formType = "horizontal"
same comment as above regarding @formType

2022-02-22 11:13 UTC, kchivorn commented on app/controllers/comments_controller.rb
> +    @formType = "stacked"
same comment as above regarding @formType

2022-02-22 11:13 UTC, kchivorn commented on app/controllers/comments_controller.rb
> +    @formType = "inline"
same comment as above regarding @formType

2022-02-22 11:14 UTC, kchivorn commented on app/views/comments/turbo/_tabs.html.erb
> +    <li class="nav-item <%= @formType == "stacked" ? "active" : "" %>" role="presentation">
same comment as above regarding @formType

2022-02-22 11:16 UTC, kchivorn commented on client/app/assets/styles/stimulus.scss
> +
Could we remove this blank line?

2022-02-22 11:18 UTC, kchivorn commented on client/app/assets/styles/stimulus.scss
> +  width: 27vw!important;
Could we add a space before !important?

2023-05-19 20:58 UTC, justin808 commented
@ahangarha can you take a look at this one?

2023-07-14 21:39 UTC, ahangarha commented
Closed in favor of #533 533

2023-07-14 21:39 UTC, closed without merging