Upgrade to Bootstrap 5. Closes #238
shakacode/react-webpack-rails-tutorial pull request #498
Opened 2022-03-27 14:28 UTC by vtamara

* Replaces `bootstrap-loader` with Bootstrap 5 loaded directly with shakapacker
* Updates navigation bar to Bootstrap 5 and changes presentation to make it somehow similar to the Bootstrap 3 version
* Upgrades `react-bootstrap` to a version that handles Bootstrap 5 and adjusts css
* Footer improved minimally

After this PR, more work is needed in transition from one demo to another  (e.g From "React Router" to "Classic").  With this PR the transition redraws full page without style and after applies style, and it is noticeable but it was not noticeable with Bootstrap 3.

2022-03-27 15:04 UTC, vtamara commented
https://user-images.githubusercontent.com/701221/160287805-be0071ed-eeef-4cb1-9f63-214642869261.mp4

2022-03-28 07:12 UTC, justin808 commented on Gemfile
> +ruby ">=2.7.5"
That's a nice option

2022-03-28 07:19 UTC, justin808 requested changes
Nice work.

Is this PR ready to merge?

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/498#-:-MzEO7CE5ENsjmX9Hxqx:bcamyws)* status: all files reviewed, 2 unresolved discussions (waiting on @vtamara)

___
*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 103 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/498#-MzENMETCxUfQoZ0YRh3:-MzENMETCxUfQoZ0YRh4:b6lgqlc) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/136f2041d657e95f8415b873abb82745b4641e12/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L103)):*
> ```JavaScript
> 
>     let ref;
>     switch (+this.state.formMode) {
> ```

what does this plus do?


<!-- Sent from Reviewable.io -->

2022-03-28 13:15 UTC, vtamara commented
> Nice work.
> 
> Is this PR ready to merge?
> 
> > Reviewed 15 of 15 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/498#-:-MzEO7CE5ENsjmX9Hxqx:bcamyws)_ status: all files reviewed, 2 unresolved discussions (waiting on @vtamara)
> 
> _[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 103 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/498#-MzENMETCxUfQoZ0YRh3:-MzENMETCxUfQoZ0YRh4:b6lgqlc) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/136f2041d657e95f8415b873abb82745b4641e12/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L103)):_
> 
> > ```js
> >     let ref;
> >     switch (+this.state.formMode) {
> > ```
> 
> what does this plus do?

IMHO it is ready to merge.

The plus converts from string to integer in case that this.state.formMode is string (for some reason it was string in my case).

2022-04-18 09:07 UTC, justin808 commented
@Judahmeek merge?

2022-09-15 08:20 UTC, justin808 commented
@vaukalak Please review and merge if CI is passing.

2023-03-15 03:23 UTC, justin808 commented
@ahangarha @Judahmeek  I think it's worth considering merging this.

2023-03-17 07:47 UTC, ahangarha commented
@vtamara Would you update your PR and resolve conflicts and CI failures?

2023-06-11 18:59 UTC, ahangarha commented
@justin808 
Is this still wanted?

2023-07-04 19:31 UTC, justin808 commented
see #528

2023-07-04 19:31 UTC, closed without merging