chore: bump major versions of client dependencies
shakacode/react-webpack-rails-tutorial pull request #529
Opened 2023-06-19 19:26 UTC by KhaledEmaraDev

1. Bump all minor and patch versions of all packages.
2. Upgrade `autoprefixer`: Use `.browserslistrc` and delete `.postcssrc` add it to `postcss.config.js` . Install and add `postcss-preset-env` to `postcss.config.js`.
3. Upgrade `immutable`: Explicitly convert all `Array`s to `List`s.
4. Upgrae `marked`: Install `marked-gfm-heading-id` to support `gfm` option.
5. Upgrade `react-router`:
  a. Remove `exact`.
  b. Use `Routes` instead of `Switch`.
  c. Import `StaticRouter` from `react-router-dom/server`.
  d. Use `element` instead of `component`.
  e. Use absolute paths instead of relative in Links.
  f. Convert Two Components to Functional React ones in order to use `useLocation` hook.
  g. Use `isActive` in `className` instead of `activeClassName`.
  h. Use `Navigate` instead of `Redirect`.
  i. Reset state once redirected.
6. Upgrade `react-transition-group`:
  a. Use `TransitionGroup` and `CSSTransition` instead of `ReactCSSTransitionGroup`.
  b. Convert one component to a Functional React one to use `forwardRef`.
  c. Add `nodeRef` as part of the state to track DOM nodes for animation.
7. Install `typescript` because it's a needed peer depenency of `prettier-eslint-cli`.

2023-06-20 18:43 UTC, ahangarha reviewed
Thanks for working on upgrading dependencies especially for transition one.

Please fix linter issues.

Also, please consider splitting changes into smaller and relevant commits. Pushing many changes in only one commit makes debugging and reviewing difficult. Many small and relevant commits are better. It helps to know the rationale behind a particular change.

2023-07-05 05:46 UTC, justin808 commented
@KhaledEmaraDev what's left here?

2023-08-07 13:55 UTC, ahangarha approved these changes
Great work 👍🏾 
Thanks to @KhaledEmaraDev for starting and @Yassa-hue for wrapping up.

To me, this PR is done.

I made two comments (which are not blocking)

2023-08-07 13:55 UTC, ahangarha commented on client/app/bundles/comments/components/CommentBox/CommentList/CommentList.jsx
> +        // http://facebook.github.io/react/docs/multiple-components.html#dynamic-children
Any React developer should know to include unique `key` to lists to avoid issues when interacting with them. We don't need to mention it here.

2023-08-10 17:52 UTC, ahangarha requested changes
Good work 👍🏾 

1. After rebasing, we have a new page for stimulus. There, we still get the following warning message:
    ![image](https://github.com/shakacode/react-webpack-rails-tutorial/assets/11241315/2f90e78a-4642-415b-995d-7e3d23caff47)

2. We had a new set of browserlist. After rebase, it is gone.
3. There are some comments from my previous review. Maybe consider applying them with the next commits for wrapping this PR up.

Our only error is related to i18n, which comes from the past and can be fixed in a separate PR.

I don't see any other issues.

2023-08-11 15:01 UTC, Yassa-hue commented on client/app/bundles/comments/components/CommentBox/CommentBox.jsx
> +import BaseComponent from 'libs/components/BaseComponent';
It's just a linting issue.

2023-08-11 17:42 UTC, ahangarha commented on client/app/bundles/comments/components/CommentBox/CommentList/CommentList.jsx
>            key={$$comment.get('id') || index}
I am concerned that this is a good key. Though it works in our case I think it is better to make ids like `comment_123`.

2023-08-11 17:42 UTC, ahangarha approved these changes
LGTM 👍🏾

2023-08-11 20:35 UTC, merged