Create Footer component (#499)
shakacode/react-webpack-rails-tutorial pull request #534
Opened 2023-07-20 15:35 UTC by Yassa-hue

This commit basically should add a footer to the Simple React page, But The footer logic is used in more than one place so a Footer component is created and called wherever it is needed.

Resolves #499

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/534)

2023-07-20 16:14 UTC, ahangarha requested changes
Good move

I see duplicate content at the bottom of the page.

![image](https://github.com/shakacode/react-webpack-rails-tutorial/assets/11241315/1215d693-7e2d-4083-892d-35588adf3258)

What do you think about the Classic Rails page? What to do there?

If we can have the same navigation bar on all pages, we should be able to have a footer too.

2023-07-20 16:35 UTC, Yassa-hue commented
Yes, Sorry for forgetting it. I removed the duplicate content.
If we want the footer on every page, I suggest putting it on the application layout with the navigation bar.

2023-07-20 18:32 UTC, ahangarha requested changes
Looks good to me.

There are minor issues to fix. After that, I think this PR is ready to get merged.

2023-07-20 18:32 UTC, ahangarha commented on client/app/bundles/comments/components/Footer/Footer.module.scss
> +}
One blank line at the end of every file

2023-07-20 18:32 UTC, ahangarha commented on client/app/bundles/comments/components/Footer/Footer.jsx
> +}
One blank line at the end of every file

2023-07-20 18:32 UTC, ahangarha commented on app/views/layouts/application.html.erb
> +
Though it doesn't matter in this case, by better to keep `<%= redux_store_hydration_data %>` at the end.

2023-07-21 13:30 UTC, ahangarha commented on app/views/layouts/application.html.erb
> +
I am amazed that our linter doesn't care about multiple blank lines. So I don't make it a blocker. To me, this PR is ready to be merged.

Good job @Yassa-hue 👍🏾

2023-07-21 13:31 UTC, ahangarha approved these changes
Good job 👍🏾

2023-07-21 13:32 UTC, ahangarha commented
@justin808 Now we have a footer on all pages. Do you have any comments here?

I think we need to update the branding in the footer. Also, the UI/UX can get improved.
I propose to have a separate task for these two.

2023-07-25 07:18 UTC, merged

2023-07-25 07:18 UTC, justin808 commented
Thanks @Yassa-hue