Add rescript example (#442)
shakacode/react-webpack-rails-tutorial pull request #552
Opened 2023-08-28 05:53 UTC by Yassa-hue

* Add rescript build configurations

* Create rescript page components

* Add rescript deps

2023-08-28 05:55 UTC, Yassa-hue commented
This PR is not ready yet. I need some help from @alex35mil to fix some issues.

2023-08-31 12:10 UTC, alex35mil requested changes
> Reviewed 24 of 29 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: all files reviewed, 32 unresolved discussions (waiting on @Yassa-hue)

___
*[`.gitignore` line 51 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA95Xa8njwCVykbVva:-NdA95Xb4o21P_YrWZX0:bac0d41) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/.gitignore#L51)):*
> ```ignore
> .yarn-integrity
> 
> lib/bs
> ```

Ignore the whole `lib` as there might be other directories in there, such as `ocaml`.
___
*[`bsconfig.json` line 15 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9ZN-BypKHFtgpMua:-NdA9ZN-BypKHFtgpMub:bc2m2am) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L15)):*
> ```JSON
>     }
>   ],
>   "bsc-flags": [
> ```

Add `-open Belt`.
___
*[`bsconfig.json` line 16 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9N4Q06yrI6ucSkxU:-NdA9N4Q06yrI6ucSkxV:b-scyews) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L16)):*
> ```JSON
>   ],
>   "bsc-flags": [
>     "-bs-super-errors",
> ```

You can remove this one.
___
*[`bsconfig.json` line 27 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9vXR56p6GxF8_nkk:-NdA9vXR56p6GxF8_nkl:b-j60dda) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L27)):*
> ```JSON
>   ],
>   "jsx": {
>   "version": 4,
> ```

Format.
___
*[`bsconfig.json` line 30 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9eeP10UqSSYA7IM0:-NdA9eeP10UqSSYA7IM1:b4hamg1) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L30)):*
> ```JSON
>     "mode": "automatic"
>   }
> }
> ```

Configure your editor to add new lines at the end of files on save.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 5 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdADCXeAB5EEW9p1kNm:-NdADCXeAB5EEW9p1kNn:bqwhgdg) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L5)):*
> ```XML
>   let (comments, setComments) = React.useState(_ => ([] : Actions.Api.comments));
>   let (error, setError) = React.useState(_ => false)
>   let (isSaving, setIsSaving) = React.useState(_ => false)
> ```

Refactor this: represent the state as a variant to eliminate the possibility of an invalid state and use reducer to manage the state.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 9 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAK8hCEtcP8JMEEvPc:-NdAK8hCEtcP8JMEEvPd:b-amtt6u) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L9)):*
> ```XML
>   let storeComment = (author, text) => {
>     setIsSaving(_ => true)
>     let _ = (async() => {
> ```

You don't need `let _ = ...` if the return value is unit.
___
*[`client/app/bundles/comments/src/RescriptPage.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAKVY_1NkoUO1xspIx:-NdAKVY_1NkoUO1xspIy:byekdee) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.bs.mjs#L1)):*
> ```JavaScript
> // Generated by ReScript, PLEASE EDIT WITH CARE
> ```

We usually gitignore this.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 8 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAL4xO9o9g9z9OBgIZ:-NdAL4xO9o9g9z9OBgI_:b-bqtgpq) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L8)):*
> ```XML
>   default: rorDefault
> }
> @module("react-on-rails") external ror: rorModule = "default";
> ```

We have these bindings: https://github.com/shakacode/rescript-react-on-rails
Please use those. 

P.S. If they are out of date, please, update them.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 20 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdALLgt3FAAMN29Xfa1:-NdALLgt3FAAMN29Xfa2:bf2ba8c) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L20)):*
> ```XML
>   headers: {.}
> }
> @module("axios") external post: (string, storeCommentData, reqOptions) => promise<unit> = "post";
> ```

Is there a reason to use `axios` instead of `fetch`?

It seems like you don't use it.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 53 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAQM2-5KPdriAt6qjI:-NdAQM2-5KPdriAt6qjJ:b-lcme39) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L53)):*
> ```XML
>     switch jsonRes->Json.decode(jsonComments) {
>       | Ok(decodedRes) => decodedRes.comments
>       | Error(err) => Js.Exn.raiseError(err)
> ```

In Rescript, use the `result` type instead of throwing an exception if an error is supposed to be handled by callers. Throw exceptions only in case of non-recoverable errors.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 57 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAQrhoEAJNMSo-onJG:-NdAQrhoEAJNMSo-onJH:bet402s) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L57)):*
> ```XML
>   }
> 
>   let storeComment = async (author: string, text: string) => {
> ```

It should be a record type.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 63 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAQxEA61f29Q5MUaz3:-NdAQxEA61f29Q5MUaz4:b-xhzhs0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L63)):*
> ```XML
>         author: author,
>         text: text
>       },
> ```

It should be encoded.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 89 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAR0tS1eyfk8vxOEDT:-NdAR0tS1eyfk8vxOEDU:ba3dfmt) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L89)):*
> ```XML
>     // } catch {
>     //   | _ => setError(_ => true)
>     // }
> ```

Remove.
___
*[`client/app/bundles/comments/src/CommentForm/CommentForm.res` line 7 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdARqV-0HYszYH9bnom:-NdARqV-0HYszYH9bnon:b-adetcn) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/CommentForm/CommentForm.res#L7)):*
> ```XML
> let make = (~storeComment: storeCommentAction, ~isSaving: bool) => {
>   let (author, setAuthor) = React.useState(_ => "")
>   let (text, setText) = React.useState(_ => "")
> ```

Define state as a record and use reducer to manage the state.
___
*[`client/app/bundles/comment [...]

2023-08-31 18:51 UTC, ahangarha commented
> @ahangarha, Can you please review the rspec test that I added ?!

I will check it on Friday

2023-09-01 00:09 UTC, mightystrong commented
*[`client/app/bundles/comments/src/RescriptPage.res` line 2 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdD00zZ2kVhSzXk9bIa:-NdD00zZ2kVhSzXk9bIb:b-xth2kw) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L2)):*
> ```XML
> @react.component
> let make = () => {
> ```

Change this to let default = () and remove the make from the ror registration. Only use make for components that are reusable and default for pages that are rendered by the rails view.


<!-- Sent from Reviewable.io -->

2023-09-01 03:10 UTC, mightystrong reviewed
> Reviewed 17 of 29 files at r1, 6 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: all files reviewed, 54 unresolved discussions (waiting on @alex35mil and @Yassa-hue)

___
*[`Procfile.dev` line 7 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdDTsT--6Fy23jcESkO:-NdDTsT--6Fy23jcESkP:bkp6cyn) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/Procfile.dev#L7)):*
> ```
> rails: bundle exec rails s -p 3000
> wp-client: HMR=true RAILS_ENV=development NODE_ENV=development bin/shakapacker-dev-server
> wp-server: bundle exec rake react_on_rails:locale && HMR=true SERVER_BUNDLE_ONLY=yes bin/shakapacker --watch
> ```

Not sure you need HMR turned on for server but I defer to @justin808 on that one?

Here's what my `Procfile.dev` looks like after full installation of React on Rails / ReScript with creating an app from scratch with latest versions of Shakapacker & React on Rails, which works without all the ENV variables declared here. But I guess it doesn't hurt to have them.

```
rails: bundle exec rails s -p 3000
wp-client: bin/shakapacker-dev-server
wp-server: SERVER_BUNDLE_ONLY=yes bin/shakapacker --watch
rescript: yarn rescript build -with-deps -w
```
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 2 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdD00zZ2kVhSzXk9bIa:-NdDaJzd9FlVoOyHoTUt:bgeo1rm) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L2)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Change this to let default = () and remove the make from the ror registration. Only use make for components that are reusable and default for pages that are rendered by the rails view.
</blockquote></details>

Instead of calling this `ReScriptPage` maybe call it `ReScriptShow.res` which is in line with controller action `def rescript` which is basically similar to a `show` action for a model.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 5 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdADCXeAB5EEW9p1kNm:-NdDUrM86U_YKAubOeMl:b-cl9b5m) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L5)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Refactor this: represent the state as a variant to eliminate the possibility of an invalid state and use reducer to manage the state.
</blockquote></details>

See here for instructions -> https://rescript-lang.org/docs/react/latest/hooks-reducer

Example code from the book.



_Code snippet:_
```XML
module Container = ChapterContainer
module Page = ChapterPage

type action =
  | ToggleView(option<Preview.t>)
  | SetScrollPosition(float)

type state = {
  view: View.t,
  preview: option<Preview.t>,
  scrollPosition: float,
}

let reducer = (state, action) => {
  switch action {
    | ToggleView(preview) => {
      switch preview {
        | None => {...state, view: Chapter, preview: preview }
        | Some(RailsDefault)
        | Some(RescriptHelloWorld)
        | Some(HelloWorld)
        | Some(HelloWorldReact)
        | Some(RescriptHelloWorldTailwind)
        | Some(RescriptHelloWorldColor) =>
        {...state, view: Preview, preview: preview }
      }}

    | SetScrollPosition(position) => {...state, scrollPosition: position}
  }
}

@react.component
let default = (~chapter: Chapter.Pagination.t) => {
  let initialState = {
    view: Chapter,
    preview: None,
    scrollPosition: 0.0,
  }

  let (state, dispatch) = React.useReducer(reducer, initialState)

  let setScroll = (event, preview) => {
    event->Scroll.scrollTop->SetScrollPosition->dispatch
    ToggleView(Some(preview))->dispatch
  }

  let scrollTo = _ => {
    ToggleView(None)->dispatch
    state.scrollPosition->Scroll.AnimateScroll.scrollTo
  }

  let setScroll = (event, preview) => setScroll(event, preview)

  {switch state.view {
    | Chapter =>
      <FramerMotion.AnimatePresense>
        <Container previous={chapter.previous} next={chapter.next}>
          <Footnotes.Provider>
            <ChapterTypeIt messages=[`Chapter ${chapter.current.number->Js.Int.toString}`, chapter.current.title] />
            <Page>
              {switch chapter.current.number {
                | 1 => <Chapter01 setScroll />
                | 2 => <Chapter02 setScroll />
                | 3 => <Chapter03 setScroll />
                | _ => React.null
              }}
              <Footnotes />
            </Page>
          </Footnotes.Provider>
        </Container>
      </FramerMotion.AnimatePresense>
    | Preview =>
      <FramerMotion.AnimatePresense>
        <PreviewBrowser onClick={scrollTo}>
          {switch state.preview {
            | Some(RailsDefault) => <PreviewRailsDefault />
            | Some(HelloWorld) => <PreviewHelloWorld />
            | Some(HelloWorldReact) => <PreviewHelloWorldReact />
            | Some(RescriptHelloWorld) => <PreviewRescriptHelloWorld color={false} />
            | Some(RescriptHelloWorldTailwind) => <PreviewRescriptHelloWorldTailwind />
            | Some(RescriptHelloWorldColor) => <PreviewRescriptHelloWorld color={true} />
            | None => React.null
          }}
        </PreviewBrowser>
      </FramerMotion.AnimatePresense>
  }}
}
```
___
*[`client/app/bundles/comments/src/RescriptPage.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAKVY_1NkoUO1xspIx:-NdCuygXAYsNwr4HdwtL:bd6zlfj) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.bs.mjs#L1)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

We usually gitignore this.
</blockquote></details>

Yes. Don’t commit the rescript generated files. These get generated when assets are precompiled for production.
___
*[`client/app/bundles/comments/src/vars.scss` line 10 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdDascy0F94n3mzLV9Z:-NdDascy0F94n3mzLV9_:b-d0wxhj) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/vars.scss#L10)):*
> ```SCSS
> // It will be used in SASS components imported as CSS Modules
> $comment-author-color: blue;
> $comment-text-color: purple;
> ```

new line
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 20 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdALLgt3FAAMN29Xfa1:-NdDVyp-3Y5fDmUkBpLa:b4ed4a7) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L20)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Is there a reason to use `axios` instead of `fetch`?

It seems like you don't use it.
</blockquote></details>

This is subjective, but as an organizational convention, I prefer to put bindings in a separate location and then name the primary binding file after the javascript. In this case, `Axios.res`. This way, there's a place for bindings as the library of binding functions grows. It makes the code easier to maintain as well as packages upgrade.

And, since this a Rails application, it makes sense to organize in a Rails-like way. So, for comments you would have a `Comment.res` model file with a `type t` that parallels the Rails model and its fields. In this case you'd have this instead of defining `type storeCommentData =...`



_Code snipp [...]

2023-09-01 03:12 UTC, mightystrong reviewed
> Reviewed 7 of 29 files at r1, 4 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: all files reviewed, 54 unresolved discussions (waiting on @alex35mil and @Yassa-hue)



<!-- Sent from Reviewable.io -->

2023-09-01 03:23 UTC, mightystrong commented
*[`client/app/bundles/comments/src/CommentForm/CommentForm.res` line 25 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdARTFO21AMpAt1Bpgf:-NdDkwtJ4OSo8XYhREim:b-j6h07) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/CommentForm/CommentForm.res#L25)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Agreed.
```
// 
@react.component
let make
```
</blockquote></details>

```
// HorizontalForm.res
@react.component
let make = () => 
. . .
```


<!-- Sent from Reviewable.io -->

2023-09-04 08:24 UTC, Yassa-hue reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: all files reviewed, 54 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`.gitignore` line 51 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA95Xa8njwCVykbVva:-NdAYbLWBk9XjcrrhF6U:b-wliy3d) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/.gitignore#L51)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Ignore the whole `lib` as there might be other directories in there, such as `ocaml`.
</blockquote></details>

The lib has other important dirs like the tasks dir!
___
*[`bsconfig.json` line 15 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9ZN-BypKHFtgpMua:-NdAYrtOCb9vSWCodngP:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L15)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Add `-open Belt`.
</blockquote></details>

Done.
___
*[`bsconfig.json` line 16 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9N4Q06yrI6ucSkxU:-NdAZoKM93Ni1r5V9p99:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L16)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

You can remove this one.
</blockquote></details>

Done.
___
*[`bsconfig.json` line 27 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9vXR56p6GxF8_nkk:-NdAZ50l257kY3KCHiVs:b2sw5lw) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L27)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Format.
</blockquote></details>

What do you mean by format?!
___
*[`bsconfig.json` line 30 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9eeP10UqSSYA7IM0:-NdAZmZg9QKujNPIsHIf:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L30)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Configure your editor to add new lines at the end of files on save.
</blockquote></details>

Done.
___
*[`Procfile.dev` line 7 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdDTsT--6Fy23jcESkO:-NdUErFJ7plv6zLiAfnA:b-bhw6is) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/Procfile.dev#L7)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Not sure you need HMR turned on for server but I defer to @justin808 on that one?

Here's what my `Procfile.dev` looks like after full installation of React on Rails / ReScript with creating an app from scratch with latest versions of Shakapacker & React on Rails, which works without all the ENV variables declared here. But I guess it doesn't hurt to have them.

```
rails: bundle exec rails s -p 3000
wp-client: bin/shakapacker-dev-server
wp-server: SERVER_BUNDLE_ONLY=yes bin/shakapacker --watch
rescript: yarn rescript build -with-deps -w
```
</blockquote></details>

I don't know if I should remove the ENV variables as It is not that relevant to my PR. What do you think?!
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 2 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdD00zZ2kVhSzXk9bIa:-NdUFjNqD3WwAz1xMv8T:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L2)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Instead of calling this `ReScriptPage` maybe call it `ReScriptShow.res` which is in line with controller action `def rescript` which is basically similar to a `show` action for a model.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 5 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdADCXeAB5EEW9p1kNm:-NdUFo5Z2tlapbx0cqHe:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L5)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

See here for instructions -> https://rescript-lang.org/docs/react/latest/hooks-reducer

Example code from the book.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 9 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAK8hCEtcP8JMEEvPc:-NdUFsc57nQaMuWLY8la:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L9)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

You don't need `let _ = ...` if the return value is unit.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAKVY_1NkoUO1xspIx:-NdAa2jQC3mCCrCBao80:b-w8ldln) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.bs.mjs#L1)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

We usually gitignore this.
</blockquote></details>

At the rescript docs I found that it's best practice to leave it so that we can see how the changes on the .res files affect the outputted .mjs files.

What do you think?!
___
*[`client/app/bundles/comments/src/vars.scss` line 10 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdDascy0F94n3mzLV9Z:-NdFEvS3CmJw1t6e886M:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/vars.scss#L10)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 8 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAL4xO9o9g9z9OBgIZ:-NdEfzyg546akO-xpk5k:bwwpm0l) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L8)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

We have these bindings: https://github.com/shakacode/rescript-react-on-rails
Please use those. 

P.S. If they are out of date, please, update them.
</blockquote></details>

It didn't work for me. Are there any missing installation steps?!
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 20 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdALLgt3FAAMN29Xfa1:-NdAb2sW3fqi8MoCAqAX:by1b5id) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L20)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

This is subjective, but as an organizational convention, I prefer to put bindings in a separate location and then name the primary binding file after the javascript. In this case, `Axios.res`. This way, there's [...]

2023-09-04 10:07 UTC, Yassa-hue commented
@ahangarha , I made the rspec tests wait for 10s before clicking the links and the test passed locally. What do you think?!

2023-09-06 18:32 UTC, mightystrong reviewed
> Reviewed 33 of 34 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: all files reviewed, 57 unresolved discussions (waiting on @alex35mil, @justin808, and @Yassa-hue)

___
*[`client/app/bundles/comments/src/RescriptPage.res` line 2 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdD00zZ2kVhSzXk9bIa:-NdfcoEq8SMUhFSPp4sp:b-qlr3ia) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L2)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@Yassa-hue This still is a `let make` function and should be `let default` so you don't have to call `make` in the registration files. In our context `make` is essentially reserved for child components. Default is used for components rendered by the rails view.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfe_5h-t4WEQWohUwI:-Ndfe_5h-t4WEQWohUwJ:b5lffkj) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L1)):*
> ```XML
> type rescriptPageStateT = {
> ```

I personally wouldn't name these like this since you're repeating the name of the `.res` file. Instead, I would name `type state = {`. So this is more readable throughout the rest of the file.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 7 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfem19DkO-oxoQQxtf:-Ndfem19DkO-oxoQQxtg:b-21akop) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L7)):*
> ```XML
> }
> 
> type rescriptPageActionT =
> ```

`type action = {`
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 14 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdffAYeEGIhgzztJ8Ea:-NdffAYfC7A_tUay0Wde:b-det2i4) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L14)):*
> ```XML
> 
> let reducer = (
>   state: rescriptPageStateT, 
> ```

This can just be `let reducer = (state, action)` since `state` and `action` are inferred by the types defined above within the module. 
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 84 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfkoKYCXeLMmEWJfRv:-NdfkoKYCXeLMmEWJfRw:b-cxqxcx) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L84)):*
> ```XML
> }
> 
> let default = make
> ```

This is not needed if simply defining has `let default` at the beginning. Unless the component will be used later as the child of another component.
___
*[`client/app/bundles/comments/src/RescriptPage.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAKVY_1NkoUO1xspIx:-NdfdUUr98rRdumWvkpf:b86eu7v) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.bs.mjs#L1)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

At the rescript docs I found that it's best practice to leave it so that we can see how the changes on the .res files affect the outputted .mjs files.

What do you think?!
</blockquote></details>

If the ReScript works, in 99.9% of the cases, the compiled JavaScript file will work. These will also be automatically generated when spinning up the server or when HMR fires. So, the only reason I can see to keep these committed is for educational purposes only. But in a production app, we wouldn't commit since they're be generated when you run `rails assets:precompile`
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 35 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfhb923rXXLIOAKjX8:-Ndfhb923rXXLIOAKjX9:baw1018) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/Actions/Actions.res#L35)):*
> ```XML
>   }
> 
>   let fetchComments = async (): result<comments, Types.errorT> => {
> ```

Remove the "T" in your type definitions.
___
*[`client/app/bundles/comments/src/Actions/Actions.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdCzSgl6kBfYLfQUvb1:-NdfhiDO1xpMySp3Ia0J:b-8m0you) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.bs.mjs#L1)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

As per above don’t commit
</blockquote></details>

Don't commit.
___
*[`client/app/bundles/comments/src/Actions/Types.res` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdffssF5KARBYNO89jG:-NdffssF5KARBYNO89jH:b9kzh8w) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/Actions/Types.res#L1)):*
> ```XML
> type formDisplayT = HorizontalForm | InlineForm | StackedFrom;
> ```

In my option, the capital Ts at the end of type definitions is unnecessary. I would also name the file specific to its purpose. In a larger application, `Types` could mean anything. This appears to be related to a form used by a model. So, I'd refactor this in the following way. Semi-colons are not needed.

```
type display = Horizontal | Inline | Stacked // Form is repetitive and inferred by a more descriptive file name of CommentForm.res

type state = {
  author: string,
  text: string,
  form: display,
}

type action = {
  | SetAuthor(string)

.
.
.
```
___
*[`client/app/bundles/comments/src/Actions/Types.bs.mjs` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfhsAXDJ4JktHCAwuB:-NdfhsAXDJ4JktHCAwuC:byp18fd) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/Actions/Types.bs.mjs#L1)):*
> ```JavaScript
> // Generated by ReScript, PLEASE EDIT WITH CARE
> ```

Remove
___
*[`client/app/bundles/comments/src/bindings/Axios.bs.mjs` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfhu4I0OdChc4pqq02:-Ndfhu4I0OdChc4pqq03:b-l6mwxj) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/bindings/Axios.bs.mjs#L1)):*
> ```JavaScript
> // Generated by ReScript, PLEASE EDIT WITH CARE
> ```

remove
___
*[`client/app/bundles/comments/src/bindings/Marked.bs.mjs` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfiUUO-SixpGdy37mn:-NdfiUUO-SixpGdy37mo:byp18fd) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/bindings/Marked.bs.mjs#L1)):*
> ```JavaScript
> // Generated by ReScript, PLEASE EDIT WITH CARE
> ```

Remove
___
*[`client/app/bundles/comments/src/bindings/ReactOnRails.res` line 2 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfiWEYAx4tMH0Zc4Lc:-NdfiWEYAx4tMH0Zc4Ld:b7l6j81) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/cl [...]

2023-09-08 21:28 UTC, Yassa-hue reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 14 of 48 files reviewed, 57 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 35 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfhb923rXXLIOAKjX8:-Ndja4Nu2mCQBktlr-6D:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/Actions/Actions.res#L35)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Remove the "T" in your type definitions.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/Actions/Types.res` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdffssF5KARBYNO89jG:-NdjaPFH0KFdTi11WkSX:b-tz46tr) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/Actions/Types.res#L1)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

In my option, the capital Ts at the end of type definitions is unnecessary. I would also name the file specific to its purpose. In a larger application, `Types` could mean anything. This appears to be related to a form used by a model. So, I'd refactor this in the following way. Semi-colons are not needed.

```
type display = Horizontal | Inline | Stacked // Form is repetitive and inferred by a more descriptive file name of CommentForm.res

type state = {
  author: string,
  text: string,
  form: display,
}

type action = {
  | SetAuthor(string)

.
.
.
```
</blockquote></details>

Done.

I'll keep the type name formDisplay without the T as display only is not entirely descriptive for me.

Also, I found similar files with the same name at other projects, so I thought applying in this PR was a good idea.
___
*[`client/app/bundles/comments/src/bindings/ReactOnRails.res` line 2 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfiWEYAx4tMH0Zc4Lc:-NdjcEkY8a5G7Bnm1wrM:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/bindings/ReactOnRails.res#L2)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Remove all semi-colons.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/CommentForm/CommentForm.res` line 4 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfidr91F3pDRe3Pz5a:-NdjcH6H596mwj7TJQgD:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/CommentForm/CommentForm.res#L4)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

Remove all the trailing "T"s from type definitions.
</blockquote></details>

Done.
___
*[`client/app/packs/client-bundle.js` line 14 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdDhYro7w_wL4wbfpkR:-NdjcfQp9i7335ugrEYU:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/packs/client-bundle.js#L14)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

@Yassa-hue In order for this to work `let make` has to be changed to `let default` in the `RescriptPage.res` file.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.bs.mjs` line 1 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAKVY_1NkoUO1xspIx:-Ndj_oBw0NQ74bes_Ko9:bchvfck) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.bs.mjs#L1)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

If the ReScript works, in 99.9% of the cases, the compiled JavaScript file will work. These will also be automatically generated when spinning up the server or when HMR fires. So, the only reason I can see to keep these committed is for educational purposes only. But in a production app, we wouldn't commit since they're be generated when you run `rails assets:precompile`
</blockquote></details>

I agree, I'll remove them.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 2 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdD00zZ2kVhSzXk9bIa:-NdjZk5u033EgVpzSL5k:b-uswbp1) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/RescriptPage.res#L2)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

@Yassa-hue This still is a `let make` function and should be `let default` so you don't have to call `make` in the registration files. In our context `make` is essentially reserved for child components. Default is used for components rendered by the rails view.
</blockquote></details>

Done.

I was just confused between your suggestion and @alex35mil 's. Any way I applied yours.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 1 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfe_5h-t4WEQWohUwI:-NdjYfDl8xEPauxNb5gN:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L1)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

I personally wouldn't name these like this since you're repeating the name of the `.res` file. Instead, I would name `type state = {`. So this is more readable throughout the rest of the file.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 7 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ndfem19DkO-oxoQQxtf:-NdjYg2g9d9YfnLAg8Ei:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L7)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

`type action = {`
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 14 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdffAYeEGIhgzztJ8Ea:-NdjYoXd7g1_0MjE_lWM:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L14)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

This can just be `let reducer = (state, action)` since `state` and `action` are inferred by the types defined above within the module.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/RescriptPage.res` line 84 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdfkoKYCXeLMmEWJfRv:-Ndj_XYf5rbNH5yoOv8D:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/client/app/bundles/comments/src/RescriptPage.res#L84)):*
<details><summary><i>Previously, mightystrong (Michael Price) wrote…</i></summary><blockquote>

This is not needed if simply defining has `let default` at the beginning. Unless the component will be used later as the child of another component.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 10:43 UTC, alex35mil requested changes
I left comments. 

Also, it's a weird place to put this example (`client/app/bundles/comments/src `). At least, rename `src` to `rescript`.

> Reviewed 1 of 34 files at r3, 2 of 3 files at r4, 21 of 34 files at r5, 1 of 3 files at r6, 14 of 18 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-:-Ni9Su_pE0vIcX__Jq05:b-2tr3jp)* status: 41 of 51 files reviewed, 54 unresolved discussions (waiting on @justin808, @mightystrong, and @Yassa-hue)

___
*[`.gitignore` line 51 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA95Xa8njwCVykbVva:-Nh0ejpQC0dwgTkh_uhq:bkzts0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/.gitignore#L51)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

The lib has other important dirs like the tasks dir!
</blockquote></details>

Then ignore `lib/ocaml`.
___
*[`bsconfig.json` line 27 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9vXR56p6GxF8_nkk:-Nh0eSOPEVs2UC5JVjaE:b-84bhvr) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L27)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

What do you mean by format?!
</blockquote></details>

I mean this line should have indentation.
___
*[`bsconfig.json` line 16 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9AkCsEtbkQW4GDkGJ:-Ni9AkCt0kfbzjx-rPT3:b-4zifas) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/bsconfig.json#L16)):*
> ```JSON
>   ],
>   "bsc-flags": ["-open JsonCombinators", "-open Belt"],
>   "suffix": ".bs.mjs",
> ```

Replace `mjs` with `js`. This should solve your issue with `rescript-react-on-rails`.
___
*[`package.json` line 93 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9AKW51VDLWWzhVwYB:-Ni9AKW51VDLWWzhVwYC:bgrooxq) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/package.json#L93)):*
> ```JSON
>     "redux-thunk": "^2.2.0",
>     "rescript": "^10.1.4",
>     "rescript-react-on-rails": "^1.0.0",
> ```

Get this back please.
___
*[`app/views/pages/rescript.html.erb` line 1 at r6](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nh0kk0Q2NKuwskiVGFF:-Nh0kk0Q2NKuwskiVGFG:bndqz7q) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e66b31d76cd5c42eb96d4f73a165bef68afa49db/app/views/pages/rescript.html.erb#L1)):*
> ```erb
> <%= react_component "RescriptShow", prerender: false %>
> ```

Why `prerender: false`?
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 8 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAL4xO9o9g9z9OBgIZ:-Ni9CxBs7-BAfGD8ne_e:b-apayz0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L8)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

It didn't work for me. Are there any missing installation steps?!
</blockquote></details>

See my comment above.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 31 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9FMXl-nKNJgvMaiR7:-Ni9FMXl-nKNJgvMaiR8:b22dnkp) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/Actions/Actions.res#L31)):*
> ```XML
>   type comments = array<t>
> 
>   type commentsResT = {
> ```

Remove `T`.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 38 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9FXw-Dq9EXKCzbcoH:-Ni9FXw-Dq9EXKCzbcoI:b-5b4b06) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/Actions/Actions.res#L38)):*
> ```XML
>     open Json.Decode
> 
>     let response = await Fetch.get("comments.json")
> ```

I don't get it. You use both `fetch` and `axios`?
___
*[`client/app/bundles/comments/src/Actions/Types.res` line 28 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9FmPT5nY9_r4me4ff:-Ni9FmPT5nY9_r4me4fg:bpcz5id) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/Actions/Types.res#L28)):*
> ```XML
> type error = NoError | FailedToSaveComment | FailedToFetchComments
> 
> type isSaving = Free | BusySaving
> ```

You should remove this module entirely and define local types for each interaction. Data fetch error is not related to data saving error and should not appear in the same type. More over, error, as well as data (if any), should be a part of the `status` type as these entities are available only in certain contexts.

See https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/ (different language, but the concept is exactly the same).
___
*[`client/app/bundles/comments/src/bindings/ReactOnRails.res` line 7 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9GZIo8mK4UfRuv3Br:-Ni9GZIp01qbonzUNu3S:bxfucut) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/bindings/ReactOnRails.res#L7)):*
> ```XML
>   default: rorDefault
> }
> @module("react-on-rails") external ror: rorModule = "default"
> ```

Replace this module with `rescript-react-on-rails`.
___
*[`client/app/bundles/comments/src/CommentForm/CommentForm.res` line 22 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdARHOYDC9yFedN1kw-:-Ni9I8fBD8rZ_f17d0Y9:b-c95v9r) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/CommentForm/CommentForm.res#L22)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

Error handling is in the ../RescriptPage.res:7
</blockquote></details>

It should be redone. See my previous comments.
___
*[`client/app/bundles/comments/src/CommentForm/forms/HorizontalForm.res` line 10 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9JR9x4icm2Kt6KuLO:-Ni9JR9x4icm2Kt6KuLP:b-a0whss) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/CommentForm/forms/HorizontalForm.res#L10)):*
> ```XML
>   ~isSaving: Types.isSaving
>   ) => {
>   <form className="form-horizontal flex flex-col gap-4"  onSubmit=handleSubmit disabled={isSaving == BusySaving}>
> ```

Use pattern matching instead of `==`. It gives exhaustiveness checking to make sure all cases are handled when the type is extended.
___
*[`client/app/bundles/comments/src/CommentForm/forms/InlineForm.res` line 13 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9JiqW5yu6BgOKOC6m:-Ni9JiqW5yu6BgOKOC6n:b-816h6l) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/CommentForm/forms/InlineForm.res#L13)):*
> ```XML
>     className="form-inline flex flex-col lg:flex-row flex-wrap gap-4"
>     onSubmit=handleSubmit
>     disabled={isSaving == BusySaving}
> ```

Same.
___
*[`client/app/bundles/comments/src/CommentForm/forms/StackedFrom.res` line 12 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9JkmVBKHSTJTq_R [...]

2023-11-02 22:00 UTC, justin808 commented
@Yassa-hue let me know when ready to merge. @Judahmeek can do it and push it...

2023-11-03 10:21 UTC, Yassa-hue commented
@justin808, the main functions are done (fetch the comments and add a new comment), I also used our [React on Rails binding](https://github.com/shakacode/rescript-react-on-rails) instead of my binding (that was the main issue that blocked the PR). What is left is some improvements on the design I think I can complete them today. (cc @alex35mil)

2023-11-03 13:44 UTC, Yassa-hue reviewed
Done!

> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-:-Ni9_FO6D7vrzOUZUCua:bs7wub4)* status: 17 of 56 files reviewed, 54 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`.gitignore` line 51 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA95Xa8njwCVykbVva:-Ni9a3sBCEMzSYkUUYz1:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/.gitignore#L51)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Then ignore `lib/ocaml`.
</blockquote></details>

Done.
___
*[`bsconfig.json` line 27 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdA9vXR56p6GxF8_nkk:-NiKPPb77UT_LjY7p16M:bk2xnzy) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/bsconfig.json#L27)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

I mean this line should have indentation.
</blockquote></details>

Sorry! I can't get the problem yet :")
___
*[`bsconfig.json` line 16 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9AkCsEtbkQW4GDkGJ:-Ni9mjiA83Vq8thYrQxi:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/bsconfig.json#L16)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Replace `mjs` with `js`. This should solve your issue with `rescript-react-on-rails`.
</blockquote></details>

Done.
___
*[`package.json` line 93 at r4](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9AKW51VDLWWzhVwYB:-Ni9mmcOB1rVmrs3qS17:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/801d68717394ae2421ac597ec909ec07fe9953e7/package.json#L93)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Get this back please.
</blockquote></details>

Done.
___
*[`app/views/pages/rescript.html.erb` line 1 at r6](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nh0kk0Q2NKuwskiVGFF:-NiK-9p13RykCdZEt1yK:bhbtsyh) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e66b31d76cd5c42eb96d4f73a165bef68afa49db/app/views/pages/rescript.html.erb#L1)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Why `prerender: false`?
</blockquote></details>

I thought the main goal of this PR was to make a rescript version of the simple react page which is `prerender: false` but it seems that it should be pre-rendered. I'll set it to true.
___
*[`client/app/bundles/comments/src/bindings/ReactOnRails.res` line 7 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9GZIo8mK4UfRuv3Br:-NiK4kc45Vic5WCjcZIs:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/bindings/ReactOnRails.res#L7)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Replace this module with `rescript-react-on-rails`.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/CommentList/AlertError/AlertError.res` line 4 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdATLKb4cx-Zwry7HKH:-NiKIB-X-Fjb5ijW1IeB:b-qcm3lf) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/CommentList/AlertError/AlertError.res#L4)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Configure your editor to autoformat files on save + remove trailing whitespaces if autoformatter is not available.
</blockquote></details>

I used the compiler formatter to format all the files at once and also added the `res:format` script to the `package.json` file
___
*[`client/app/bundles/comments/src/CommentList/AlertError/AlertError.res` line 6 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAT_eaEWxKgSyof16b:-NiKLKSnBVSrmlxA2jkX:b-72n1j4) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/CommentList/AlertError/AlertError.res#L6)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

There are different options:
https://github.com/webpack-contrib/css-loader#separating-interoperable-css-only-and-css-module-features
https://github.com/Coobaha/postcss-variables-loader
</blockquote></details>

We don't use SCSS vars anymore. I'm not sure what you mean.
___
*[`client/app/bundles/comments/src/ReScriptShow.res` line 3 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9Bdi347PIPriqtvhi:-NiK0h2v4axZahZmvo7t:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/ReScriptShow.res#L3)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Error should be a part of the `status` type.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/src/ReScriptShow.res` line 4 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9BGfZ-uDzdo7wzFC1:-Ni9fSh79GsU7AGxADd0:bhggjqy) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/ReScriptShow.res#L4)):*
> Why `Types` module?

Because this type is needed in multiple files. When I tried to put it on the `RescriptShow.res` and call it in `CommentForm.res` I faced a `dependency cycle` error. My idea is to use a file that contains all types that are used in several files in the `Types.res` file. I agree the naming is not the best we can do. I suggest making a types file for the `ReScriptShow.res` component and putting on it all the types we need. We can call it a `local type` then.

Regarding this line of code specifically:
I don't think the form needs to know the status of the saving anyway it just needs a bool value to indicate if it should be disabled or not so I'll create the local type as you suggested and pass only a bool value `disabled` to the form.
___
*[`client/app/bundles/comments/src/ReScriptShow.res` line 27 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9B0d9Cy1R8RsXmCU7:-NiKPg3c4gmiFdGBsHIG:b-s3who5) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/ReScriptShow.res#L27)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Setup rescript integration in your editor. It will enable auto-formatting.
</blockquote></details>

Done! I used the compiler format.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 8 at r2](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NdAL4xO9o9g9z9OBgIZ:-NiK18Sq4NUe7uyZXoHo:bg45wz0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/71efa7fd6bde336d0b4258185b31c2d08964940f/client/app/bundles/comments/src/Actions/Actions.res#L8)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

See my comment above.
</blockquote></details>

Done! They aren't out of date the js file extension was wrong (as you explained on Slack). I found that we don't need to bind the `authenticityHeaders` we can use the `authenticityToken` function to set the headers directly. see the [implementation](https://github.com/shakacode/react_on_rails/blob/249c69812474e0f532df432581bf5e618df0e1ec/node_package/src/Authenticity.ts#L13C1-L18C1).
___
*[`client/app/bundles [...]

2023-11-07 14:41 UTC, alex35mil requested changes
> Reviewed 4 of 45 files at r5, 3 of 25 files at r7, 7 of 38 files at r8, 15 of 19 files at r9, 20 of 20 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 28 unresolved discussions (waiting on @justin808, @mightystrong, and @Yassa-hue)

___
*[`client/app/bundles/comments/rescript/bindings/Axios.res` line 9 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieC92l0VXdzXAzScyX:-NieC92l0VXdzXAzScyY:b-wmpedh) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/bindings/Axios.res#L9)):*
> ```XML
>   author: string,
>   text: string,
> }
> ```

It is unrelated to `axios`, so it should be moved elsewhere.
___
*[`client/app/bundles/comments/rescript/Header/Header.bs.mjs` line 95 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieCpLY2AONQwbZM0G9:-NieCpLY2AONQwbZM0GA:ba3dfmt) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/Header/Header.bs.mjs#L95)):*
> ```JavaScript
>   make ,
> }
> /* react/jsx-runtime Not a pure module */
> ```

Remove.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 38 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9FXw-Dq9EXKCzbcoH:-NieBKoH2e0mCUP5fac4:b-klx624) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/Actions/Actions.res#L38)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

As I said above, this page is meant to be a rescript copy of the simple React page. we use Axios because we set the headers during the post request and Fetch because it's a simple and direct fetch. It's the same as we do in the simple React page.
</blockquote></details>

Regardless, this is weird, as setting headers via Fetch is not a problem. You can keep it as is here, but don't use such a pattern in the real-world project. There's no reason to.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 7 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieDDr995-krzD40j8Q:-NieDDr995-krzD40j8R:b6libdm) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/ReScriptShow.res#L7)):*
> ```XML
>   commentStoreError: bool,
>   saving: savingStatus,
> }
> ```

Did you read the article I linked earlier regarding an illegal state?


<!-- Sent from Reviewable.io -->

2023-11-10 10:43 UTC, Yassa-hue reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 28 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`client/app/bundles/comments/rescript/bindings/Axios.res` line 9 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieC92l0VXdzXAzScyX:-NisoDb0DT3nc12xOasq:b4hc40x) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/bindings/Axios.res#L9)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

It is unrelated to `axios`, so it should be moved elsewhere.
</blockquote></details>

I don't think we should use a record with a specific type in Axios binding at all. the data should be an object with an undetermined number of keys and values, and so the request options.
___
*[`client/app/bundles/comments/rescript/Header/Header.bs.mjs` line 95 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieCpLY2AONQwbZM0G9:-NisF2h8BXNEZXkYmsmS:bb7f2mf) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/Header/Header.bs.mjs#L95)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

done
___
*[`client/app/bundles/comments/src/ReScriptShow.res` line 4 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9BGfZ-uDzdo7wzFC1:-NiYvnxf82q5gneOSWuy:brpnshq) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/ReScriptShow.res#L4)):*
<details><summary><i>Previously, Yassa-hue (Yassa Tamer) wrote…</i></summary><blockquote>

> Why `Types` module?

Because this type is needed in multiple files. When I tried to put it on the `RescriptShow.res` and call it in `CommentForm.res` I faced a `dependency cycle` error. My idea is to use a file that contains all types that are used in several files in the `Types.res` file. I agree the naming is not the best we can do. I suggest making a types file for the `ReScriptShow.res` component and putting on it all the types we need. We can call it a `local type` then.

Regarding this line of code specifically:
I don't think the form needs to know the status of the saving anyway it just needs a bool value to indicate if it should be disabled or not so I'll create the local type as you suggested and pass only a bool value `disabled` to the form.
</blockquote></details>

I removed all the types files. I used local types.
___
*[`client/app/bundles/comments/src/Actions/Actions.res` line 38 at r7](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Ni9FXw-Dq9EXKCzbcoH:-NisFQKt1Epffhak3hHr:bveirs0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/50f562d31fe9680e78aa1a908a0406bb501bb8d6/client/app/bundles/comments/src/Actions/Actions.res#L38)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Regardless, this is weird, as setting headers via Fetch is not a problem. You can keep it as is here, but don't use such a pattern in the real-world project. There's no reason to.
</blockquote></details>

NOTED!
I'll create an issue to use the same function for get and post requests in `SimpleReactPage` and `Rescript page`.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 7 at r10](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NieDDr995-krzD40j8Q:-Nisosos1l0Tp9cFSvJW:b5i7rwf) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/e328420b13d9d70084b892bd5f06ece8b0bbb380/client/app/bundles/comments/rescript/ReScriptShow.res#L7)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Did you read the article I linked earlier regarding an illegal state?
</blockquote></details>

Done.
We agreed on the implementation plan on slack.


<!-- Sent from Reviewable.io -->

2023-11-13 13:24 UTC, alex35mil requested changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 30 unresolved discussions (waiting on @justin808, @mightystrong, and @Yassa-hue)

___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 5 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7pVfg5_6LBqRdJI6h:-Nj7pVfg5_6LBqRdJI6i:b-yzbue2) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L5)):*
> ```XML
> type commentsFetchStatus =
>   | FetchError
>   | CommentsFetched(Actions.Fetch.comments)
> ```

It should be a single type.

State:

```rescript
{
  commentsFetchStatus: NotStarted,
  commentsStoreStatus: CommentsFetched(comments),
}
```

is invalid, but still possible with the current design.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 94 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7q2Sd3ENNpFHwLBTK:-Nj7q2Se8fz7pR0sx1-N:be7o9n4) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L94)):*
> ```XML
>         disabled={switch state.commentsStoreStatus {
>         | BusyLoading => true
>         | _ => false
> ```

Don't use passthrough. It invalidates the benefits of exhaustiveness.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 98 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qIdPBGOD7YG8WZLv:-Nj7qIdPBGOD7YG8WZLw:b-816h6l) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L98)):*
> ```XML
>         storeCommentError={switch state.commentsStoreStatus {
>         | StoreError => true
>         | _ => false
> ```

Same.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 106 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qJ__Ew5LWTrFCIhq:-Nj7qJ__Ew5LWTrFCIhr:bb73xfv) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L106)):*
> ```XML
>         comments={switch state.commentsFetchStatus {
>         | CommentsFetched(comments) => comments
>         | _ => []
> ```

Same
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 110 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qKUTEr08SJwMQXwy:-Nj7qKUTEr08SJwMQXwz:b-816h6l) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L110)):*
> ```XML
>         fetchCommentsError={switch state.commentsFetchStatus {
>         | FetchError => true
>         | _ => false
> ```

Same.


<!-- Sent from Reviewable.io -->

2023-11-13 14:40 UTC, Yassa-hue reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 30 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 5 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7pVfg5_6LBqRdJI6h:-Nj82Qa04aVOYamzmcuc:b-adnv9m) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L5)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

It should be a single type.

State:

```rescript
{
  commentsFetchStatus: NotStarted,
  commentsStoreStatus: CommentsFetched(comments),
}
```

is invalid, but still possible with the current design.
</blockquote></details>

How is that possible?! When I tried the state you provided it didn't compile:



_Code snippet:_
```XML
  32 ┆ reducer,
  33 ┆ {
  34 ┆   commentsFetchStatus: NotStarted,
  35 ┆   commentsStoreStatus: CommentsFetched(comments),
  36 ┆ },

  This variant expression is expected to have type commentsFetchStatus
  The constructor NotStarted does not belong to type commentsFetchStatus

FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 94 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7q2Sd3ENNpFHwLBTK:-Nj86JGC43DWIfnDcjEb:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L94)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Don't use passthrough. It invalidates the benefits of exhaustiveness.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 98 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qIdPBGOD7YG8WZLv:-Nj86Juq-4VbFurfWYbl:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L98)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 106 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qJ__Ew5LWTrFCIhq:-Nj86YuW2Og-zBeaXRcz:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L106)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`client/app/bundles/comments/rescript/ReScriptShow.res` line 110 at r11](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-Nj7qKUTEr08SJwMQXwy:-Nj86ZOzBLvvjqkgrFN3:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b50e9e39a14de4e074ea94af74231d5fdf8ee74c/client/app/bundles/comments/rescript/ReScriptShow.res#L110)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-15 10:21 UTC, alex35mil requested changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 27 unresolved discussions (waiting on @justin808, @mightystrong, and @Yassa-hue)

___
*[`client/app/bundles/comments/rescript/CommentForm/CommentForm.res` line 3 at r12](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NjHUJZu07AfwvAxdQx6:-NjHUJZu07AfwvAxdQx7:b-tdftox) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/0edbefdf35023c6405dcf203dae0d3513b21ab13/client/app/bundles/comments/rescript/CommentForm/CommentForm.res#L3)):*
> ```XML
> type formDisplay = Horizontal | Inline | Stacked
> 
> type commentsStoreStatus = Idle | BusyLoading | StoreError
> ```

Rename it to `status` or `savingStatus`.

```rescript
type status = 
  | Idle
  | Saving
  | Error
```


<!-- Sent from Reviewable.io -->

2023-11-15 10:40 UTC, Yassa-hue reviewed
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552)* status: 66 of 69 files reviewed, 27 unresolved discussions (waiting on @alex35mil, @justin808, and @mightystrong)

___
*[`client/app/bundles/comments/rescript/CommentForm/CommentForm.res` line 3 at r12](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-NjHUJZu07AfwvAxdQx6:-NjHYDsi1LkpLWQeCXUm:b-896fja) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/0edbefdf35023c6405dcf203dae0d3513b21ab13/client/app/bundles/comments/rescript/CommentForm/CommentForm.res#L3)):*
<details><summary><i>Previously, alex35mil (Alex) wrote…</i></summary><blockquote>

Rename it to `status` or `savingStatus`.

```rescript
type status = 
  | Idle
  | Saving
  | Error
```
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-11-15 10:48 UTC, alex35mil approved these changes
Looking good.

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/552#-:-NjHa6NF0neffamMMBuf:br2sbrj)* status: 66 of 69 files reviewed, 26 unresolved discussions (waiting on @justin808, @mightystrong, and @Yassa-hue)



<!-- Sent from Reviewable.io -->

2023-11-16 10:13 UTC, Yassa-hue commented
@justin808 I think the failing tests are fake faluires. The tests pass on the local run.
<img width="662" alt="Screenshot 2023-11-16 at 12 10 10 PM" src="https://github.com/shakacode/react-webpack-rails-tutorial/assets/58339464/dc5f7608-2ba9-4a52-896c-d69d1ad5ab32">

2023-11-17 23:31 UTC, merged